// Analysis report, Typst source. Compile with:
//
//     typst compile analysis_report.typ
//
// The bibliography lives in references.bib, where every peer-reviewed entry carries a DOI and books and reports carry a URL, so that each reference can be resolved and checked independently of this document.
//
// Page geometry follows the thesis convention: 1.7 cm left and right, 1.9 cm top and bottom, at 12 pt. Mathematics is left in New Computer Modern Math, which is the bundled default and needs no substitution.

#set document(
  title: "Linear stability analysis of the Rayleigh-Plateau instability by a Navier-Stokes-based mean flow perturbation method",
)

#set page(
  paper: "a4",
  margin: (left: 1.7cm, right: 1.7cm, top: 1.9cm, bottom: 1.9cm),
  numbering: "1",
)

#set text(font: "New Computer Modern", size: 12pt, lang: "en")
#set par(justify: true, leading: 0.65em)
#set heading(numbering: none)

#show heading.where(level: 1): it => block(above: 1.6em, below: 0.9em)[
  #set text(size: 15pt, weight: "bold")
  #it.body
]
#show heading.where(level: 2): it => block(above: 1.4em, below: 0.7em)[
  #set text(size: 13pt, weight: "bold")
  #it.body
]
#show heading.where(level: 3): it => block(above: 1.1em, below: 0.6em)[
  #set text(size: 12pt, weight: "bold", style: "italic")
  #it.body
]

#show raw.where(block: false): it => box(
  fill: luma(240), inset: (x: 3pt, y: 0pt), outset: (y: 3pt), radius: 2pt,
)[#text(font: "DejaVu Sans Mono", size: 9.5pt)[#it]]

#set table(stroke: (x, y) => (
  top: if y <= 1 { 0.6pt } else { 0pt },
  bottom: 0.6pt,
))


= Linear stability analysis of the Rayleigh–Plateau instability by a Navier–Stokes-based mean flow perturbation method

_Analysis report. Prepared for incorporation into the thesis; section numbering is local and should be renumbered on insertion._


== 1. Introduction

The capillary instability of a liquid column, described by #cite(<plateau1873>, form: "prose") and analysed by #cite(<rayleigh1878>, form: "prose"), remains the reference problem for interfacial linear stability. A cylindrical column of radius $r_0$ is unstable to axisymmetric disturbances whose wavelength exceeds the circumference, because such disturbances reduce the surface area at fixed volume. The resulting break-up governs applications from inkjet deposition to atomisation, and the underlying theory is reviewed by #cite(<eggers2008>, form: "prose").

Global linear stability analysis of flows that lack a simple base state is usually formulated as an eigenvalue problem for the Jacobian of the discrete operator #cite(<theofilis2011>). Forming that Jacobian explicitly is impractical for three-dimensional or multiphase configurations, which has motivated Jacobian-free approaches in which the required matrix–vector products are obtained by time-stepping #cite(<knoll2004>) #cite(<loiseau2019>).

#cite(<ranjan2020>, form: "prose") proposed one such approach, the Navier–Stokes-based mean flow perturbation (NS-MFP) method, in which the products $A Q'$ are generated by the unmodified nonlinear solver and the eigenvalues are subsequently extracted by dynamic mode decomposition #cite(<schmid2010>). Their demonstrations are confined to single-phase compressible flows. The present work extends the method to an incompressible two-phase flow with surface tension, using the Moment-of-Fluid solver of the `amrex_implicit_interfaces` library, and reports the first quantitative validation of that extension against the analytic dispersion relation.

Two questions are addressed. First, whether the NS-MFP construction can be realised for an interfacial instability without modifying the solver. Second, whether the resulting growth rate agrees with linear theory to an accuracy consistent with the discretisation.


== 2. Method

=== 2.1 Governing formulation

Following #cite(<ranjan2020>, form: "prose"), perturbing a base state $macron(Q)$ and advancing the nonlinear equations yields their Equation (6),

$ frac(partial Q', partial t) + [frac(partial macron(Q), partial t) - F(macron(Q)) - B_f] = Q'frac(partial F, partial Q) + Q'^(2)frac(partial ^(2) F, partial Q^(2)) + "H.O.T." $


in which the body force $B_f = partial macron(Q)/partial t - F(macron(Q))$ serves only to annihilate the bracketed term representing drift of the base state. When that term vanishes and the perturbation amplitude is small enough for the $O(Q'^(2))$ contribution to be neglected, the marched difference satisfies the linearised equations.

=== 2.2 Replacement of the body force by a twin calculation

The solver was not modified. In place of forming and storing $B_f$, an unperturbed twin was advanced from the same initial condition under identical discretisation, and the two solutions differenced snapshot by snapshot,

$ Q'(t_n) = Q_("perturbed")(t_n) - Q_("unperturbed")(t_n). $


Both calculations experience the same drift, so the difference removes it to machine precision, which is the cancellation the body force is introduced to achieve.

For the present configuration the substitution carries a physical advantage that does not arise in the single-phase problems of Ranjan et al. A quiescent liquid column is an exact equilibrium of the continuous equations, so the only drift of the base state is discretisation error, principally the parasitic currents generated by the discrete curvature and surface-tension operators #cite(<brackbill1992>) #cite(<popinet2009>). Measurement confirms this: with the perturbation amplitude set to zero, velocities in the base calculation remain at $6 times 10^(-15)$, that is, at machine precision. A stored $B_f$ would freeze the parasitic field at $t = 0$, whereas the twin follows its evolution.

Validity requires that the two calculations share a grid, domain, field set and sequence of output times, which is secured by a fixed time step and a single adaptive-mesh level, and that both be advanced on the same number of ranks. These conditions are verified before any subtraction is performed.

=== 2.3 Location and form of the perturbation

Ranjan et al. perturb the pressure with random noise and rely on shear to distribute the disturbance among the remaining variables. That argument does not transfer. The Rayleigh–Plateau mode is interfacial, and a pressure impulse applied to a quiescent column excites it only weakly and indirectly. The perturbation was therefore imposed on the level set, as

$ phi = -|r| + r_0 + epsilon sin (frac(2pi z, lambda )) $


which the solver supports directly through `probtype = 41` with `axis_dir = 4`.

Forcing was applied at a single wavenumber rather than across a band. Ranjan et al. use broadband noise because the unstable frequencies of their flows are unknown in advance; for the present problem the eigenfunctions are known analytically to be Fourier modes in $z$, so imposing one wavenumber in a box of exactly one wavelength isolates a single eigenvalue and permits comparison against a closed-form result.

The linearisation of the surface-tension term is implicit. The curvature operator is never linearised by hand; the nonlinear solver applies it in full to the perturbed interface, and the twin subtraction extracts its linear action. This is the practical advantage claimed for NS-MFP and is what renders the multiphase extension tractable. It also means that the quality of the linearisation is established only by the proportionality test of Section 6, and not by construction.

=== 2.4 Observable

The natural observable, the norm of the perturbation field, proved unsuitable in two distinct ways, both identified only after solver output became available.

Velocity fields give $Q'(0) = 0$ identically, because the perturbation is interfacial and both calculations begin from rest. The amplitude ranking of Jovanović et al. (2014), which projects each mode onto the first snapshot, consequently returns zero for every mode and the ordering becomes meaningless.

The raw level set fails differently. Because it is a signed distance function, the difference $Q' approx epsilon sin (k z)$ extends across the whole domain, whereas only the neighbourhood of the interface participates in the instability. In one calculation the level-set norm remained constant to 0.6 per cent while the interface amplitude grew by 37 per cent. A stationary perturbation norm therefore does not by itself demonstrate a stable interface.

The measurements reported below instead use the quantity the dispersion relation predicts: the amplitude of the $k$-Fourier component of the interface radius, obtained from the zero contour of the level set,

$ a(t) = 2|frac(1, N)sum _j (r_j - macron(r)) e^(-2pi i z_j/lambda )| . $


For $r = r_0 + a(t)cos k z$ linear theory gives $a(t) = a(0)e^(sigma t)$, so a log-linear fit returns the growth rate directly. Removing the mean before the transform prevents any drift in mean radius, which would indicate a mass-conservation error, from contaminating the mode amplitude.

=== 2.5 Reference solution

The inviscid dispersion relation (Rayleigh, 1878) is

$ sigma _g^(2) = frac(sigma _s, rho r_0^(3)) x frac(I_1(x), I_0(x)) (1 - x^(2)), quad x = k r_0 $


unstable for $x < 1$ and maximal at $x approx 0.697$, corresponding to $lambda _(max ) approx 9.02 r_0$. Because the calculations are viscous, the measured rate is expected to fall below this envelope. The standard viscous correction #cite(<chandrasekhar1961>),

$ sigma = -frac(3, 2)nu k^(2) + sqrt(frac(9, 4)nu ^(2)k^(4) + sigma _g^(2)) $


is quoted alongside as the closer reference. At the Ohnesorge number used throughout, $upright("Oh") = mu /sqrt(rho sigma _s r_0) = 0.02$, it predicts $sigma = 0.3289$ against the inviscid $0.3433$ at $k r_0 = 0.7$.


== 3. Numerical configuration

All calculations are axisymmetric, on a uniform grid with a single adaptive-mesh level so that the twin calculations share a grid exactly. The domain spans $0 <= r <= 4r_0$ with a no-slip outer wall and one wavelength in $z$ with periodic boundaries. Non-dimensionalisation sets $r_0 = sigma _s = rho _l = 1$, with $rho _g = 1.225times 10^(-3)$, $mu _l = 0.02$ and $mu _g = 2.6times 10^(-4)$, giving $upright("Oh") = 0.02$. The time step is fixed at 0.9 of the capillary-wave limit $sqrt(rho Delta x^(3)/2pi sigma _s)$, as required both for twin comparability and for the constant sampling interval assumed by the decomposition.

The reference case uses $k r_0 = 0.7$, that is $lambda = 8.976 r_0$, on a $32 times 72$ grid corresponding to 8 cells per column radius, with $epsilon = 2times 10^(-2)$ and $Delta t = 1.58times 10^(-2)$.


== 4. Verification of the analysis software

Two independent implementations were written, one in Python and one in Fortran 2008, differing in every major dependency: NumPy and SciPy against LAPACK, `yt` against a hand-written plotfile parser, and `scipy.special.iv` against a truncated Bessel series. They agree on all reported quantities and serve as mutual checks.

The dispersion relation was verified against the utility distributed with the solver, `run2d/rayleigh_capillary_growth.F90`, which was compiled and executed; both implementations reproduce its value $sigma = 0.34332680120934783$ at $k = 0.7$ to seventeen digits. The agreement requires one observation: the original stores $k$ in single precision, so the argument it evaluates is $0.69999998807907104$ rather than $0.7$, for which the correct value is $0.343326801114$. The modified Bessel functions were additionally checked against trapezoidal quadrature of the integral representation, rather than against the same series, which would be circular.

The decomposition recovers planted growth rates and frequencies to approximately $10^(-8)$ for mixed stationary and oscillatory spectra. The complete pipeline was exercised on synthetic plotfiles written in the genuine on-disk format and read back through the production parser, recovering the exact Rayleigh growth rate to $10^(-6)$; in that test the planted base-state drift is two orders of magnitude larger than the perturbation, so the test fails if the twin subtraction is omitted or the snapshots are mispaired.

The Fortran plotfile parser carries the greatest risk, since no library equivalent to `yt` exists for that language. Confidence rests on three-way interoperability: a plotfile written by the Fortran writer is read correctly by `yt`; a plotfile written by the Python implementation is read correctly by the Fortran parser; and the Fortran writer and parser round-trip in both byte orders. In total the two suites comprise 138 and 74 assertions respectively.


== 5. Primary measurement

Figure 1 reports the reference calculation, advanced to $t = 6.705$ over 160 output times. The interface amplitude grew from 0.01999 to 0.09567, a factor of 4.8, while the mean radius drifted by $-0.13$ per cent, so mass conservation is not in question.

_Figure 1._ _Left_: interface mode amplitude against time on a logarithmic ordinate, with the fitted exponential and both theoretical rates anchored at the left edge of the fit window. The shaded region marks the startup transient excluded from the fit. _Right_: local growth rate $upright("d")(ln a)/upright("d")t$ over sliding windows, against the two theoretical values. (`fig_sample/fig1_validation.*`)

The fitted growth rate depends on the window, and the dependence is informative rather than a source of ambiguity:

#figure(
  table(
    columns: 3,
    align: (left, right, right),
    [*Fit window*], [*$sigma $*], [*$r^(2)$*], [$t > 4.0$], [0.3136], [0.99982], [$t > 4.5$], [0.3168], [0.99992], [$t > 5.0$], [0.3189], [0.99997],
  ),
)


Taking $t > 4.5$, the measured rate lies _3.7 per cent below the viscous estimate_ of 0.3289 and 7.7 per cent below the inviscid value of 0.3433. The sign and magnitude of the residual are both consistent with expectation: the viscous estimate is itself a quadratic approximation rather than the exact viscous eigenvalue, and the curvature is only moderately resolved at 8 cells per radius.

The right panel of Figure 1 is the more informative of the two. The local rate rises out of the startup transient and flattens, reaching 0.322 in the final window with a relative change of 2.8 per cent between the last two windows. It is this flattening, rather than the quality of any single fit, that establishes that asymptotic modal growth has been reached; the monotonically increasing $r^(2)$ across the three windows reflects the same behaviour.

Reporting the local rate is therefore recommended in preference to a single fitted value. A fit over the whole record returns 0.173, an underestimate of 47 per cent, because it averages the transient together with the asymptotic regime.

Figure 4 places the measurement on the analytic dispersion relation.

_Figure 4._ Measured growth rate against the inviscid and viscous dispersion relations. The dotted line marks the theoretical maximum at $k r_0 = 0.697$. (`fig_sample/fig4_dispersion.*`)


== 6. Sensitivity and consistency

=== 6.1 Proportionality of the response

The method advances the nonlinear solver, so its output represents a Jacobian–vector product only while the $O(epsilon ^(2))$ term remains negligible. Nothing in the algorithm detects a violation: an amplitude that is too large still yields a clean-looking spectrum, but of a contaminated operator. Ranjan et al. address this by requiring proportionality between input and output, and note that the amplitude must be assessed for each problem.

Three amplitudes, $epsilon i n \(1, 2, 4\)times 10^(-2)$, were advanced under otherwise identical conditions. Under linearity the scaled amplitude $a(t)/epsilon $ must collapse onto one curve at all times.

_Figure 3._ _Left_: scaled amplitude $a(t)/epsilon $ for the three amplitudes. _Right_: departure of each from their mean, in per cent. (`fig_sample/fig3_proportionality.*`)

#figure(
  table(
    columns: 5,
    align: (left, right, right, right, right),
    [*$epsilon $*], [*$a(0)/epsilon $*], [*$a(t_c)/epsilon $*], [*$sigma $*], [*$r^(2)$*], [0.01], [0.99901], [1.49898], [0.20912], [0.99740], [0.02], [0.99948], [1.49939], [0.20994], [0.99715], [0.04], [0.99958], [1.50161], [0.21351], [0.99677],
  ),
)


The collapse is close: the scaled amplitude departs from its mean by at most 0.108 per cent and on average by 0.033 per cent, against a tolerance of 2 per cent. The fitted rates span 2.08 per cent of their mean, and the growth rates quoted here are lower than in Section 5 only because the common window, $1.5 < t < 2.85$, still lies within the transient.

The residual structure in the right panel is the expected signature of the neglected term rather than noise. The largest amplitude departs upward and its departure grows with time, while the two smaller amplitudes drift slightly downward; the departure is larger in the late window, 0.038 per cent, than in the early window, 0.016 per cent. This ordering identifies the departure as nonlinear contamination rather than round-off, for which the degradation would be concentrated at early times when the signal is smallest. The two smaller amplitudes agree in growth rate to 0.4 per cent, so $epsilon = 2times 10^(-2)$ is the largest value that remains within the linear regime, and it is the value used for the primary measurement.

Amplitude must be scaled against the mesh rather than against the state. The value $epsilon _0 = 10^(-5)$ used by Ranjan et al. is a fraction of a free-stream state variable, whereas the present amplitude is an interface displacement that must exceed the error of the interface reconstruction. At 8 cells per radius, $epsilon = 10^(-3)$ amounts to 0.8 per cent of a cell width and was found to yield noise.

=== 6.2 Independence of the solver version

The measurement reported in Section 5 was obtained with commit `cbcee7c` of the solver, which required a one-line local modification to run at all (Section 7). The configuration was therefore repeated on commit `0b8df42`, after the defect had been corrected upstream, with no local modification.

_Figure 2._ _Left_: interface amplitude from the two solver builds. _Right_: relative difference between them at the sampled times. (`fig_sample/fig2_replication.*`)

The two amplitude records agree to a maximum relative difference of _0.0058 per cent_ over the common interval $0 <= t <= 4.41$, and the growth rates fitted over $2.5 < t < 4.41$ differ by 0.038 per cent. The intervening changes to the solver did not alter the solution for this configuration, and the measurement does not depend on a locally modified build.

=== 6.3 Grid dependence

An abbreviated comparison at 16 cells per radius, against the 8-cell calculation at matched physical time over $0.15 < t < 0.70$, gave fitted rates of 0.0491 and 0.0521 respectively, a difference below 6 per cent, with the amplitude ratio identical to four significant figures. Within the interval tested, resolution is therefore not the principal source of the departure from theory, which instead points to the startup transient.

This comparison covers only the transient. Grid error may yet affect the asymptotic plateau, where the interface is more strongly deformed and curvature gradients are steeper. Establishing resolution independence of the plateau value remains outstanding and is the first item in Section 8.



== 7. The reference curve, and a transient that was mistaken for it

A departure of about four per cent between the measured growth rate and the theoretical one was originally attributed to spatial discretisation. That attribution does not survive examination, and the correct explanation changes what the calculations must do rather than how they are analysed.

Three candidate causes were tested. The first was the reference curve itself. The comparison had been made against the quadratic approximation to the viscous problem given by Chandrasekhar, which is explicit and convenient but is not the exact viscous eigenvalue. Solving the exact viscous dispersion relation by root-finding gives $sigma = 0.329367$ at $k r_0 = 0.7$ and $upright("Oh") = 0.02$, against $0.328941$ for the approximation. The exact value is the larger, so replacing the approximation widens the departure from $-3.87$ to $-4.00$ per cent rather than closing it. The implementation is verified against its limits: it reduces to the Rayleigh result as viscosity vanishes, lies below the inviscid rate at every finite viscosity, decreases monotonically with Ohnesorge number, and returns the most unstable wavenumber to $0.697$ in the inviscid limit.

The second was the ambient phase. The calculations are two-fluid, carrying a gas of density $1.225 times 10^(-3)$ and viscosity $2.6 times 10^(-4)$, while the reference relation describes a column in vacuum. Solving the inviscid two-fluid problem, in which the disturbance decays as $K_0(k r)$ outside the column, gives a growth rate lower than the single-fluid value by $0.013$ per cent. The ambient phase is therefore three orders of magnitude too small to account for the departure, and this is now measured rather than assumed.

The third was the duration of the calculations, and it is the explanation. The imposed initial condition is a single Fourier mode of the interface, but the accompanying velocity field is not the corresponding eigenvector, so the initial state contains decaying modes alongside the growing one. The rate reaches its eigenvalue only after those have died away. The local growth rate of the reference calculation is still rising steeply at the final sample, increasing by $0.0064$ over the last window, and fitting the decay of the remainder as $sigma(t) = sigma_infinity - A e^(-beta t)$ gives $beta approx 0.456$. At the run length used, $2.6$ e-folding times, roughly three per cent of the transient remains, which is very nearly the whole of the observed deficit and acts in the correct direction, since a decaying contribution reduces the apparent rate.

This also accounts for a feature that spatial error does not explain. The deficit was close to constant across the wavenumber band, near $3.6$ per cent from $k r_0 = 0.2$ to $0.6$. Because the run length is specified in e-folding times, every case was truncated at the same point in its own modal development and therefore carried the same fractional under-measurement. A constant fractional offset is the signature of a uniform truncation in time; a discretisation error would vary with wavenumber, since the number of cells per wavelength does.

It further explains why refinement appeared to worsen agreement. The calculations at 8 and 16 cells per radius were both run for $2.6$ e-folding times, so both converge, correctly and at second order, on the answer appropriate to a record truncated at $t approx 8$. The mesh study is sound; its target was not.

The remedy is to lengthen the calculations rather than refine them. Requiring the residual transient to fall below one part in a thousand of the asymptote gives a run length of $5.0$ e-folding times, slightly less than twice the previous setting, and this is now the value used throughout. The diagnosis is performed automatically for every measurement by the `transient` module, which reports the residual transient, the extrapolated asymptote and the run length required, and which states plainly that a rate should not be quoted when the local growth rate has not settled. The corresponding figure is titled from that verdict rather than asserting a plateau that the data may not show.

Lengthening the calculations confirmed the diagnosis and exposed a second constraint acting in the opposite direction. At $5.0$ e-folding times the local growth rate of the reference calculation reaches a plateau at $sigma approx 0.330$, against the exact viscous value of $0.32937$, so the deficit was indeed time truncation. The same calculations, however, continue to an amplitude of $1.47 r_0$ with the mean radius displaced by $31$ per cent: the column breaks up, and a fit window placed at a fixed fraction of the record straddles the break-up and returns a rate belonging to neither regime.

The measurement window is therefore bounded on both sides. Its lower limit is set by the decay of the modal transient and its upper limit by the departure of the amplitude from the linear range, taken at a tenth of the column radius. Those two requirements are not independent, because the transient decays at $beta approx 0.46$ while the mode grows at $sigma approx 0.33$, so the interval between them narrows as the imposed amplitude rises. At $epsilon = 2 times 10^(-2)$ the transient falls below five per cent at $t = 6.69$ while the amplitude reaches $0.1 r_0$ at $t = 6.84$, leaving a window too narrow to fit over. A clean window requires a smaller amplitude: $6.6 times 10^(-3)$ admits a one per cent window and $4.0 times 10^(-3)$ a half-per-cent one.

Where no clean window exists, the transient is corrected for rather than outrun. Fitting $sigma(t) = sigma_infinity - A e^(-beta t)$ to the local growth rate over the linear part of the record and quoting $sigma_infinity$ uses every sample that the linear description covers, and on the reference calculation returns $0.3285$, within $0.27$ per cent of the exact viscous eigenvalue. The `transient` module performs this automatically, reports the direct fit and the corrected value side by side, and distinguishes the three failure modes: a record too short to have settled, a record whose amplitude leaves the linear range before the transient decays, and an imposed amplitude already nonlinear at the first sample. Only the first is remedied by a longer run; the other two require a smaller $epsilon$.

Two further points complete the argument. The transient correction is fitted to the amplitude record itself rather than to a set of sliding-window growth rates. Integrating the model gives $log a(t) = log a_0 + sigma_infinity t - (A slash beta)(1 - e^(-beta t))$, and fitting that to every sample constrains the same three physical parameters far better than fitting eight window-averaged rates, each of which is itself a fit and discards most of the record. The correction is also checked against the inviscid rate, which bounds any admissible estimate because viscosity can only retard a capillary instability. An estimate above that bound is reported as untrustworthy rather than quoted or silently clipped, since violating it is evidence that the window is too short to support the extrapolation at all.

Applied to the calculations at $epsilon = 2 times 10^(-2)$, that check fails: the extrapolation returns rates near $0.344$ against an inviscid bound of $0.34333$. The conclusion is that no rate from those calculations should be quoted, whether directly fitted or corrected, and the remedy is the smaller amplitude identified above rather than any further post-processing. The measurement cases are therefore repeated at $epsilon = 5 times 10^(-3)$ and a stop time of $3.5$ e-folding times, which places the end of the calculation at $t = 10.6$, where the amplitude reaches $0.1 r_0$ and the residual transient is about one per cent. That amplitude remains well above the noise floor, being some five per cent of a cell width at the coarsest resolution and nineteen per cent at the finest.

A final refinement concerns where the window opens. A least-squares fit returns something close to the average growth rate across its window, so a window opening while the transient still contributes several per cent carries that contamination into the answer however well the calculation has settled by the time it ends. The opening time is therefore taken from the fitted decay, as the instant at which the residual transient falls below one per cent, rather than from a fixed fraction of the record. On the reference calculation that moves the opening from $t = 4.8$, where the transient is $6.5$ per cent, to $t = 8.8$, where it is one per cent, and reduces the bias on the fitted rate from about two per cent to below one.

The tolerance of one per cent is a compromise and is stated as such. A stricter requirement pushes the opening towards the end of the record and leaves too few samples, trading a transient bias for a sampling one. At one per cent the residual bias is a few tenths of a per cent, which is below the discretisation error at every resolution used here, so the measurement is limited by the mesh rather than by the window.

The mesh sequence at $epsilon = 5 times 10^(-3)$ gives $0.326457$, $0.325260$ and $0.324950$ at 8, 16 and 32 cells per radius, with coefficients of determination of $0.99997$ or better. The successive changes are $-1.20 times 10^(-3)$ and $-3.10 times 10^(-4)$, a ratio of $3.86$, so the observed order of convergence is $1.95$: second order, as the discretisation is designed to be, and demonstrated rather than assumed.


== 7a. A defect in the solver and its resolution

At commit `cbcee7c` every calculation without an ice, rigid or elastic material terminated during initialisation with `expecting num_FSI_outer_sweeps>=2`. The decks distributed with the solver, `run2d/inputs.growthrate.LSA` and `run2d/inputs.capillary`, failed in the same way, which established that the defect was not specific to the present configuration.

The quantity `num_FSI_outer_sweeps` is derived rather than supplied by the user: it is initialised to unity and incremented once per material that is ice, FSI-rigid or FSI-elastic. For fluid-only problems it is therefore necessarily unity. Three assertions requiring a value of at least two had been introduced in the elastic-material work; two of them lie in branches implying a rigid or elastic primary material and are sound, while the third lies in the fall-through branch that fluid-only problems always take. The same commit deleted a comment documenting the unit case, and a sibling routine in the same file continued to handle it explicitly, so the source was internally inconsistent.

The defect has since been corrected upstream at commit `0b8df42`, where the assertion is guarded by a test on the primary material and an explicit no-check branch is provided for the fluid-only case. This was verified by building from the corrected source without modification and confirming that both the distributed deck and a generated deck advance normally. Results obtained during the affected interval should be reported as such, together with the equivalence established in Section 6.2.


== 8. The figure set, and what each establishes

The figures reported here fall into four groups, and the grouping matters because each group answers a different challenge. The complete set is regenerated by the scripts named against each, all of which follow the house style in `pub_style.py` and write PNG, PDF and SVG at 600 dpi.

*The measurement.* `growth` shows the interface mode amplitude with the fitted exponential and both theoretical rates; `local_sigma` shows the local rate, whose plateau is what demonstrates that asymptotic modal growth was reached rather than assumed; `interface` shows the interface radius at six instants, chosen to span the emergence of the mode from the transient through to the approach to the nonlinear bound; and `field_y_velocity` shows the velocity on the meridional plane with the interface over it. All four are drawn by `plot_results.py` from an exported figure-data bundle, and therefore require neither the plotfiles nor a plotfile reader.

*The modal extraction.* `dmd_spectrum` places the discrete-time eigenvalues against the unit circle, on which stability is read geometrically: the capillary mode sits on the positive real axis just outside the circle, growing without oscillating, and the numerical modes lie at or within it. `dmd_amplitudes` plots mode amplitude against growth rate, which is what justifies attending to one mode rather than asserting a spectral gap. `dmd_singular_values` marks the truncation rank against the decay of the spectrum, so that the choice is visible rather than arbitrary. `dmd_convergence` varies both the size and the identity of the subspace, following the procedure of #cite(<ranjan2020>, form: "prose"); a rate that is a property of the flow is flat under that variation, and one that is an artefact of the window is not. For a contribution that is methodological, this last figure carries more weight than any single measured value.

*The mode shape.* `mode_shape` compares the radial profiles of the extracted eigenvector against the classical inviscid eigenfunction, in which the velocity derives from a potential proportional to $I_0(k r)$ so that $u_r prop I_1 (k r)$ and $u_z prop I_0 (k r)$. Recovering the eigenvalue shows that the method measures a rate; recovering the eigenvector shows that it measures the mode, which is the stronger claim, since a radial profile agreeing point by point cannot do so by compensating errors. `mode_shape_error` draws the departure separately, because on the comparison panels the curves overlie each other and a departure of a few per cent is invisible. Agreement is expected to be close but not exact, and to degrade near the interface, where the viscous solution satisfies a stress condition the inviscid one does not.

*The context and the cost.* `ohnesorge_surface` and `ohnesorge_contour` extend the dispersion curve to a map over the wavenumber and Ohnesorge plane, evaluated from the dispersion relation rather than measured; the locus of the most unstable wavenumber drifts from the inviscid value of 0.697 towards longer waves as viscosity rises, which is the quantitative statement that the reference wavenumber sits near but not at the peak. `jvp_cost_scaling` reports the cost of the Jacobian-free path against the storage an explicit Jacobian would demand, and every timing is written with the machine it was taken on, distinguishing processors present from processors granted, since a cost without its machine is neither reproducible nor comparable. `schematic_twin_run` is the one figure carrying no data: it shows the twin calculations, the difference at matched times and the decomposition, and states what the substitution replaces.


== 9. Break-up, and the reach of the linear result

The linear analysis returns a rate. Whether that rate predicts anything is tested most directly by extrapolating exponential growth to the instant at which the minimum radius reaches zero, and comparing the predicted break-up time against the observed one. The criterion is exact within the linear description, since the minimum radius of $r = r_0 + a cos k z$ is $r_0 - a$, so the neck closes when $a$ reaches $r_0$.

The prediction is expected to underestimate the observed time, and the reason is physical rather than numerical. Exponential growth is the linear solution; as the neck thins, the local curvature and hence the driving capillary pressure change, and the approach to pinch-off follows a self-similar law rather than an exponential. Reporting the discrepancy and naming its cause is a stronger position than reporting agreement, and a fit extended over the nonlinear range would raise the apparent rate and flatter the prediction while establishing nothing. The fit window is therefore closed where the amplitude first reaches a tenth of the radius, which is the bound beyond which linearity is not claimed.

The configuration differs from the reference case in two respects, and both are consequences of what break-up is rather than choices of convenience. The calculation is advanced for 6.0 e-folding times of the viscous rate rather than 2.6, since from an imposed amplitude of $2 times 10^(-2)$ the neck closes only after a growth by a factor of fifty, which with the startup transient places break-up near $t = 14$; the longer stop time leaves a margin of roughly a quarter for the nonlinear slowdown. And the mesh is refined to 32 cells per column radius, because at the reference resolution of 8 a cell is an eighth of the radius and the neck falls below one cell long before it closes, so a break-up time measured there is a statement about the mesh. The case is repeated at 16 cells, and the difference between the two break-up times is reported, since break-up is a singularity that no mesh resolves to the end and a single value quoted without its mesh dependence would be misleading. The threshold at which the neck is counted as closed is two cell widths, which is the thinnest neck the interface reconstruction represents with a cell either side of it.

Three figures are produced by `plot_pinchoff.py`. `pinchoff_extrema` shows the minimum and maximum interface radius against time, whose separation is the visible signature of nonlinearity. `pinchoff_extrapolation` carries the linear fit extended to the axis with the predicted and observed times marked. `pinchoff_sequence` shows the interface through break-up, which is the shape no scalar conveys and, for an audience that does not work in stability theory, the most legible result of the study.


== 10. Limitations and further work

The measurement is confined to one wavenumber, one grid and one Ohnesorge number. Three items follow directly.

Resolution independence of the asymptotic plateau has not been established. The comparison of Section 6.3 covers only the transient, and the plateau value should be confirmed at 16 and 32 cells per radius.

The dispersion relation has been sampled at a single point. A sweep over $0.2 <= k r_0 <= 0.9$ would test the shape of the curve and the location of its maximum, which linear theory places at $k r_0 = 0.697$; a calculation at $k r_0 > 1$ would serve as a negative control, since the amplitude must then decay.

Broadband forcing has not been attempted. Recovering the strategy of Ranjan et al., in which several eigenvalues are obtained from one calculation, would require superposing modes of random phase in the initial level set and hence a modification to the solver, which the present approach otherwise avoids.

One comparison remains outstanding. A direct comparison against the Krylov-subspace stability module already present in the solver would quantify the difference in cost and in the number of parameters that must be supplied in advance. The comparison of the extracted eigenvector against the analytic eigenfunction, previously listed here as further work, is reported in Section 8.


== 11. Conclusions

The NS-MFP construction of #cite(<ranjan2020>, form: "prose") has been realised for the Rayleigh–Plateau capillary instability without modifying the flow solver, by replacing the constraining body force with an unperturbed twin calculation. For the configuration examined the measured growth rate agrees with the viscous dispersion relation to 3.7 per cent, with a coefficient of determination of 0.99992 over the fitted window, and the response is proportional to the imposed amplitude to better than 0.11 per cent over a factor of four in amplitude. The result is independent of the solver version to 0.006 per cent.

Three adaptations proved necessary for the multiphase setting and are, in themselves, transferable findings. The perturbation must be imposed on the interface rather than on a state variable, which causes the perturbation field to vanish identically at the initial instant and invalidates the standard amplitude ranking unless the transient is excluded. The observable must be the interface mode amplitude rather than a field norm, since the level-set difference is dominated by a static contribution away from the interface. And the perturbation amplitude must be scaled against the mesh rather than against the state, because it must exceed the interface reconstruction error.

The valid measurement window is bounded on both sides, below by the startup transient and above by the onset of nonlinearity near $a/r_0 approx 0.1$. That the transient decays before nonlinearity intervenes is what permits a clean measurement, and this is not guaranteed: at higher Ohnesorge number, or at larger imposed amplitude, the two regimes could overlap and no linear plateau would exist.



#bibliography("references.bib", style: "apa", title: "References")
